name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@add3486cc3b55d4a5e11c8045058cef96538edc7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}